(function() {var implementors = {};
implementors["clang"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"clang/enum.AlignofError.html\" title=\"enum clang::AlignofError\">AlignofError</a>",synthetic:false,types:["clang::error::AlignofError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"clang/enum.OffsetofError.html\" title=\"enum clang::OffsetofError\">OffsetofError</a>",synthetic:false,types:["clang::error::OffsetofError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"clang/enum.SaveError.html\" title=\"enum clang::SaveError\">SaveError</a>",synthetic:false,types:["clang::error::SaveError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"clang/enum.SizeofError.html\" title=\"enum clang::SizeofError\">SizeofError</a>",synthetic:false,types:["clang::error::SizeofError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"clang/enum.SourceError.html\" title=\"enum clang::SourceError\">SourceError</a>",synthetic:false,types:["clang::error::SourceError"]},];
implementors["glob"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glob/struct.GlobError.html\" title=\"struct glob::GlobError\">GlobError</a>",synthetic:false,types:["glob::GlobError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glob/struct.PatternError.html\" title=\"struct glob::PatternError\">PatternError</a>",synthetic:false,types:["glob::PatternError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
