(function() {var implementors = {};
implementors["clang"] = [{text:"impl&lt;'r&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"clang/completion/struct.CompletionResult.html\" title=\"struct clang::completion::CompletionResult\">CompletionResult</a>&lt;'r&gt;",synthetic:false,types:["clang::completion::CompletionResult"]},{text:"impl&lt;'r&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"clang/completion/struct.CompletionString.html\" title=\"struct clang::completion::CompletionString\">CompletionString</a>&lt;'r&gt;",synthetic:false,types:["clang::completion::CompletionString"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"clang/diagnostic/enum.Severity.html\" title=\"enum clang::diagnostic::Severity\">Severity</a>",synthetic:false,types:["clang::diagnostic::Severity"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"clang/struct.Usr.html\" title=\"struct clang::Usr\">Usr</a>",synthetic:false,types:["clang::Usr"]},];
implementors["glob"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"glob/struct.Pattern.html\" title=\"struct glob::Pattern\">Pattern</a>",synthetic:false,types:["glob::Pattern"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"glob/struct.MatchOptions.html\" title=\"struct glob::MatchOptions\">MatchOptions</a>",synthetic:false,types:["glob::MatchOptions"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
